Update run-test.yaml

diff --git a/.github/workflows/run-test.yaml b/.github/workflows/run-test.yaml
--- a/.github/workflows/run-test.yaml
+++ b/.github/workflows/run-test.yaml
@@ -33,7 +33,7 @@ jobs:
       # 2️⃣ Set up Docker image
       - name: Build Docker image
         run: |
-          docker build -t dataextraction:latest .
+          docker build -t data-extraction:latest .
 
       # 3️⃣ Set up KinD cluster
       - name: Create KinD cluster
@@ -51,7 +51,7 @@ jobs:
           ./bin/install_common_templates_to_helm.sh
       
       - name: Load Docker image into KinD
-        run: kind load docker-image dataextraction:latest --name ci-sample
+        run: kind load docker-image data-extraction:latest --name ci-sample
       
       - name: create traininghost namespace
         run: kubectl create namespace traininghost
@@ -76,18 +76,21 @@ jobs:
       #     echo "✅ PostgreSQL installation complete."
       #     kubectl get pods -n traininghost -l app.kubernetes.io/name=postgresql
       
-      # - name: Mock secrets for modelmgmtService
-      #   run: |
-      #     set -euo pipefail
-      #     NAMESPACE=traininghost
+      - name: Mock secrets for data-extraction
+        run: |
+          set -euo pipefail
+          NAMESPACE=traininghost
 
-      #     echo "🔧 Creating namespace if missing..."
-      #     kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
+          echo "🔧 Creating namespace if missing..."
+          kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
 
-      #     echo "🔐 Creating mock secret: leofs-secret"
-      #     kubectl create secret generic leofs-secret \
-      #       --from-literal=password="dummy-s3-secret-key" \
-      #       -n $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
+          echo "🔐 Creating mock secret: cassandra"
+          # kubectl create secret generic leofs-secret \
+          #   --from-literal=password="dummy-s3-secret-key" \
+          #   -n $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
+
+          kubectl create secret generic cassandra -n $NAMESPACE\
+          --from-literal=cassandra-password='MyStrongP@ssw0rd!'
 
       - name: install data-extraction
         run: |
@@ -107,8 +110,8 @@ jobs:
           kubectl get pods -n $NAMESPACE --no-headers | awk '$3 != "Running" {print $1}' | \
             xargs -r -I {} kubectl describe pod {} -n $NAMESPACE || true
 
-          echo "⏳ Waiting for all pods in namespace '$NAMESPACE' to be Ready (max 300s)..."
-          if ! kubectl wait --for=condition=Ready pod --namespace $NAMESPACE --all --timeout=300s; then
+          echo "⏳ Waiting for all pods in namespace '$NAMESPACE' to be Ready (max 100s)..."
+          if ! kubectl wait --for=condition=Ready pod --namespace $NAMESPACE --all --timeout=100s; then
             echo "❌ Timeout waiting for pods. Dumping debug info..."
             echo "🔹 Current pod states:"
             kubectl get pods -n $NAMESPACE -o wide || true
